version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: family-tree-postgres
    environment:
      POSTGRES_DB: family_tree
      POSTGRES_USER: family_tree_user
      POSTGRES_PASSWORD: family_tree_password
      # PostgreSQL 한글 설정
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    ports:
      - "5432:5432"
    volumes:
      # 데이터 영속성
      - postgres_data:/var/lib/postgresql/data
      # 초기화 SQL 스크립트 (필요시)
      # - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U family_tree_user -d family_tree"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - family-tree-network

  # pgAdmin (선택사항 - PostgreSQL 관리 도구)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: family-tree-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@familytree.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - family-tree-network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  family-tree-network:
    driver: bridge